# Generated by Django 4.0.4 on 2022-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.TextField(verbose_name='Предмет')),
                ('actualhomework', models.TextField(verbose_name='Актуальное дз')),
            ],
            options={
                'verbose_name': 'Актуальное дз',
                'verbose_name_plural': 'Актуальные дз',
            },
        ),
    ]
