# Generated by Django 4.0.4 on 2022-09-04 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplines',
            old_name='actualhomework',
            new_name='actual_homework',
        ),
        migrations.AddField(
            model_name='disciplines',
            name='actual_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='homework', verbose_name='Дз файл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplines',
            name='eng_discipline',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Предмет на англ'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DisciplineHomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_discipline', models.TextField(verbose_name='Предмет на англ')),
                ('actual_homework', models.TextField(verbose_name='Дз')),
                ('actual_file', models.FileField(upload_to='homework', verbose_name='Дз файл')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.disciplines', verbose_name='Домашка какого предмета')),
            ],
            options={
                'verbose_name': 'Все дз',
                'verbose_name_plural': 'Все дз',
            },
        ),
    ]
