# Generated by Django 4.0.4 on 2022-09-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_rename_actualhomework_disciplines_actual_homework_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.RemoveField(
            model_name='disciplines',
            name='actual_file',
        ),
        migrations.RemoveField(
            model_name='disciplines',
            name='actual_homework',
        ),
        migrations.CreateModel(
            name='DisciplinesActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_discipline', models.TextField(verbose_name='Предмет на англ')),
                ('actual_homework', models.TextField(verbose_name='Актуальное дз')),
                ('actual_file', models.FileField(upload_to='homework', verbose_name='Дз файл')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.disciplines', verbose_name='Домашка какого предмета')),
            ],
            options={
                'verbose_name': 'Актуальное дз',
                'verbose_name_plural': 'Актуальные дз',
            },
        ),
    ]
