# Generated by Django 4.1 on 2022-09-05 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_disciplines_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinehomework',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата дз'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplinesactual',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата дз'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplinehomework',
            name='actual_file',
            field=models.FileField(null=True, upload_to='homework', verbose_name='Дз файл'),
        ),
        migrations.AlterField(
            model_name='disciplinesactual',
            name='actual_file',
            field=models.FileField(null=True, upload_to='homework', verbose_name='Дз файл'),
        ),
    ]
